services:
  postgres:
    container_name: ya-diplom-2-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "praktikum"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"