// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: internal/interfaces/grpc/proto/user_secret.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserSecret) Reset() {
	*x = UserSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSecret) ProtoMessage() {}

func (x *UserSecret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSecret.ProtoReflect.Descriptor instead.
func (*UserSecret) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP(), []int{0}
}

func (x *UserSecret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSecret) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserSecret) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateUserSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret *UserSecret `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *CreateUserSecretRequest) Reset() {
	*x = CreateUserSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserSecretRequest) ProtoMessage() {}

func (x *CreateUserSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateUserSecretRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserSecretRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateUserSecretRequest) GetSecret() *UserSecret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type CreateUserSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *CreateUserSecretResponse) Reset() {
	*x = CreateUserSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserSecretResponse) ProtoMessage() {}

func (x *CreateUserSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateUserSecretResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserSecretResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteUserSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUserSecretRequest) Reset() {
	*x = DeleteUserSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserSecretRequest) ProtoMessage() {}

func (x *DeleteUserSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserSecretRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserSecretRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteUserSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *DeleteUserSecretResponse) Reset() {
	*x = DeleteUserSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserSecretResponse) ProtoMessage() {}

func (x *DeleteUserSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserSecretResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserSecretResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserSecretsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Page  int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetUserSecretsRequest) Reset() {
	*x = GetUserSecretsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSecretsRequest) ProtoMessage() {}

func (x *GetUserSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSecretsRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserSecretsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetUserSecretsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetUserSecretsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secrets    []*UserSecret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Page       int64         `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages int64         `protobuf:"varint,3,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	Error      string        `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *GetUserSecretsResponse) Reset() {
	*x = GetUserSecretsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSecretsResponse) ProtoMessage() {}

func (x *GetUserSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSecretsResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserSecretsResponse) GetSecrets() []*UserSecret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *GetUserSecretsResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserSecretsResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetUserSecretsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_interfaces_grpc_proto_user_secret_proto protoreflect.FileDescriptor

var file_internal_interfaces_grpc_proto_user_secret_proto_rawDesc = []byte{
	0x0a, 0x30, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x22, 0x48, 0x0a, 0x0a, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x22, 0x30, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3f, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x41, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d,
	0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x07, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0x92, 0x02, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12,
	0x57, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x64,
	0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_interfaces_grpc_proto_user_secret_proto_rawDescOnce sync.Once
	file_internal_interfaces_grpc_proto_user_secret_proto_rawDescData = file_internal_interfaces_grpc_proto_user_secret_proto_rawDesc
)

func file_internal_interfaces_grpc_proto_user_secret_proto_rawDescGZIP() []byte {
	file_internal_interfaces_grpc_proto_user_secret_proto_rawDescOnce.Do(func() {
		file_internal_interfaces_grpc_proto_user_secret_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_interfaces_grpc_proto_user_secret_proto_rawDescData)
	})
	return file_internal_interfaces_grpc_proto_user_secret_proto_rawDescData
}

var file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_interfaces_grpc_proto_user_secret_proto_goTypes = []any{
	(*UserSecret)(nil),               // 0: diploma.UserSecret
	(*CreateUserSecretRequest)(nil),  // 1: diploma.CreateUserSecretRequest
	(*CreateUserSecretResponse)(nil), // 2: diploma.CreateUserSecretResponse
	(*DeleteUserSecretRequest)(nil),  // 3: diploma.DeleteUserSecretRequest
	(*DeleteUserSecretResponse)(nil), // 4: diploma.DeleteUserSecretResponse
	(*GetUserSecretsRequest)(nil),    // 5: diploma.GetUserSecretsRequest
	(*GetUserSecretsResponse)(nil),   // 6: diploma.GetUserSecretsResponse
}
var file_internal_interfaces_grpc_proto_user_secret_proto_depIdxs = []int32{
	0, // 0: diploma.CreateUserSecretRequest.secret:type_name -> diploma.UserSecret
	0, // 1: diploma.GetUserSecretsResponse.secrets:type_name -> diploma.UserSecret
	1, // 2: diploma.UserSecrets.CreateUserSecret:input_type -> diploma.CreateUserSecretRequest
	3, // 3: diploma.UserSecrets.DeleteUserSecret:input_type -> diploma.DeleteUserSecretRequest
	5, // 4: diploma.UserSecrets.GetUserSecrets:input_type -> diploma.GetUserSecretsRequest
	2, // 5: diploma.UserSecrets.CreateUserSecret:output_type -> diploma.CreateUserSecretResponse
	4, // 6: diploma.UserSecrets.DeleteUserSecret:output_type -> diploma.DeleteUserSecretResponse
	6, // 7: diploma.UserSecrets.GetUserSecrets:output_type -> diploma.GetUserSecretsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_interfaces_grpc_proto_user_secret_proto_init() }
func file_internal_interfaces_grpc_proto_user_secret_proto_init() {
	if File_internal_interfaces_grpc_proto_user_secret_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateUserSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateUserSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUserSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUserSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserSecretsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserSecretsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_interfaces_grpc_proto_user_secret_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interfaces_grpc_proto_user_secret_proto_goTypes,
		DependencyIndexes: file_internal_interfaces_grpc_proto_user_secret_proto_depIdxs,
		MessageInfos:      file_internal_interfaces_grpc_proto_user_secret_proto_msgTypes,
	}.Build()
	File_internal_interfaces_grpc_proto_user_secret_proto = out.File
	file_internal_interfaces_grpc_proto_user_secret_proto_rawDesc = nil
	file_internal_interfaces_grpc_proto_user_secret_proto_goTypes = nil
	file_internal_interfaces_grpc_proto_user_secret_proto_depIdxs = nil
}
